# Generated by Django 3.2.2 on 2021-05-31 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
